//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFCC_Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFCC_Helper.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid damage.
        /// </summary>
        internal static string bonus_avoid_damage {
            get {
                return ResourceManager.GetString("bonus_avoid_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat flying enemies.
        /// </summary>
        internal static string bonus_defeat_flying_enemies {
            get {
                return ResourceManager.GetString("bonus_defeat_flying_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat enemies with focus attacks.
        /// </summary>
        internal static string bonus_defeat_with_focus_attacks {
            get {
                return ResourceManager.GetString("bonus_defeat_with_focus_attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat enemies with spell fusion.
        /// </summary>
        internal static string bonus_defeat_with_spell_fusion {
            get {
                return ResourceManager.GetString("bonus_defeat_with_spell_fusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat enemies with spells.
        /// </summary>
        internal static string bonus_defeat_with_spells {
            get {
                return ResourceManager.GetString("bonus_defeat_with_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge attacks.
        /// </summary>
        internal static string bonus_dodge_attacks {
            get {
                return ResourceManager.GetString("bonus_dodge_attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge thrown rocks.
        /// </summary>
        internal static string bonus_dodge_thrown_rocks {
            get {
                return ResourceManager.GetString("bonus_dodge_thrown_rocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t cast spells.
        /// </summary>
        internal static string bonus_dont_cast_spells {
            get {
                return ResourceManager.GetString("bonus_dont_cast_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t heal allies.
        /// </summary>
        internal static string bonus_dont_heal_allies {
            get {
                return ResourceManager.GetString("bonus_dont_heal_allies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t heal yourself.
        /// </summary>
        internal static string bonus_dont_heal_yourself {
            get {
                return ResourceManager.GetString("bonus_dont_heal_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t pick anything up.
        /// </summary>
        internal static string bonus_dont_pick_anything_up {
            get {
                return ResourceManager.GetString("bonus_dont_pick_anything_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t use focus attacks.
        /// </summary>
        internal static string bonus_dont_use_focus {
            get {
                return ResourceManager.GetString("bonus_dont_use_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t use physical attacks.
        /// </summary>
        internal static string bonus_dont_use_physical {
            get {
                return ResourceManager.GetString("bonus_dont_use_physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eat lots of food.
        /// </summary>
        internal static string bonus_eat_lots_of_food {
            get {
                return ResourceManager.GetString("bonus_eat_lots_of_food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish as quickly as possible.
        /// </summary>
        internal static string bonus_finish_quickly {
            get {
                return ResourceManager.GetString("bonus_finish_quickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflict damage.
        /// </summary>
        internal static string bonus_inflict_damage {
            get {
                return ResourceManager.GetString("bonus_inflict_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Treasure Chests.
        /// </summary>
        internal static string bonus_open_treasure_chests {
            get {
                return ResourceManager.GetString("bonus_open_treasure_chests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up items.
        /// </summary>
        internal static string bonus_pick_up_items {
            get {
                return ResourceManager.GetString("bonus_pick_up_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up magicite.
        /// </summary>
        internal static string bonus_pick_up_magicite {
            get {
                return ResourceManager.GetString("bonus_pick_up_magicite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up money.
        /// </summary>
        internal static string bonus_pick_up_money {
            get {
                return ResourceManager.GetString("bonus_pick_up_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take magical damage.
        /// </summary>
        internal static string bonus_take_magical_damage {
            get {
                return ResourceManager.GetString("bonus_take_magical_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take physical damage.
        /// </summary>
        internal static string bonus_take_physical_damage {
            get {
                return ResourceManager.GetString("bonus_take_physical_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown bonus).
        /// </summary>
        internal static string bonus_unknown {
            get {
                return ResourceManager.GetString("bonus_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use items.
        /// </summary>
        internal static string bonus_use_items {
            get {
                return ResourceManager.GetString("bonus_use_items", resourceCulture);
            }
        }
    }
}
